name: CI/CD Pipeline for Databricks Bundle

on:
  pull_request:
    branches:
      - main
  push:
    branches: 
      - main
  workflow_dispatch:
    inputs:
      env:
        description: 'Deployment environment (Non-prod or prod)'
        required: true
        default: 'non-prod'

jobs:
  validate-and-deploy:
    name: Deploy to Databricks (${{ github.event.inputs.env || 'auto' }})
    runs-on: ubuntu-latest
    environment: ${{ github.event.inputs.env || 'non-prod' }}
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'

      - name: Install dependencies
        run: |
          cd dab_trips
          pip install -r requirements-dev.txt

      - name: Setup Databricks CLI
        uses: databricks/setup-cli@main

      - name: Determine Environment
        id: set-env
        run: |
          if [[ "${{ github.event_name }}" == "workflow_dispatch" ]]; then
            echo "env=${{ github.event.inputs.env }}" >> $GITHUB_OUTPUT
          elif [[ "${{ github.event_name }}" == "pull_request" ]]; then
            echo "env=non-prod" >> $GITHUB_OUTPUT
          elif [[ "${{ github.event_name }}" == "push" ]]; then
            echo "env=prod" >> $GITHUB_OUTPUT
          fi

      - name: Load Environment Secrets
        run: |
          ENV="${{ steps.set-env.outputs.env }}"
          echo "Selected Environment: $ENV"
          echo "DATABRICKS_BUNDLE_ENV=$ENV" >> $GITHUB_ENV

          if [[ "$ENV" == "non-prod" ]]; then
            echo "DATABRICKS_HOST=${{ secrets.DATABRICKS_HOST }}" >> $GITHUB_ENV
            echo "DATABRICKS_CLIENT_ID=${{ secrets.DATABRICKS_CLIENT_ID }}" >> $GITHUB_ENV
            echo "DATABRICKS_CLIENT_SECRET=${{ secrets.DATABRICKS_CLIENT_SECRET }}" >> $GITHUB_ENV
            echo "DATABRICKS_TENANT_ID=${{ secrets.DATABRICKS_PROD_TENANT_ID }}" >> $GITHUB_ENV
          elif [[ "$ENV" == "prod" ]]; then
            echo "DATABRICKS_HOST=${{ secrets.DATABRICKS_HOST }}" >> $GITHUB_ENV
            echo "DATABRICKS_CLIENT_ID=${{ secrets.DATABRICKS_CLIENT_ID }}" >> $GITHUB_ENV
            echo "DATABRICKS_CLIENT_SECRET=${{ secrets.DATABRICKS_CLIENT_SECRET}}" >> $GITHUB_ENV
            echo "DATABRICKS_TENANT_ID=${{ secrets.DATABRICKS_TENANT_ID }}" >> $GITHUB_ENV
          else
            echo "Unsupported environment: $ENV"
            exit 1
          fi

      - name: Validate and Deploy Bundle
        run: |
          cd dab_trips
          databricks bundle validate
          databricks bundle deploy --target=$DATABRICKS_BUNDLE_ENV --auto-approve
